ERM-1608: Add count of populated terms in accordion header
folio-org/ui-licenses pull request #464
Opened 2021-06-02 09:28 UTC by peterboehm

2021-06-04 13:10 UTC, EthanFreestone requested changes

2021-06-04 13:10 UTC, EthanFreestone commented on src/components/viewSections/Terms.js
> +      const count = Object.keys(customProperties).length;
I think we want populated terms, not just all terms, something like:

```
      const count = Object.keys(customProperties).filter(cp => !!cp.value).length
```

(idk if that exactly will work)

2021-06-09 11:33 UTC, peterboehm reviewed
the test procedure added to the issue description works fine for me locally

2021-06-14 10:18 UTC, EthanFreestone approved these changes

2021-06-14 10:19 UTC, merged